protected/modules/roles/controllers/UsuariosController.php
<?php
class UsuariosController extends Controller
{
	public $modulo = "usuarios";
	
	/**
	 *
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 *      using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = '//layouts/column2';
        
         public function behaviors() {
        return array(
            'eexcelview' => array(
                'class' => 'application.extensions.eexcelview.EExcelBehavior',
            ),
        );
    }
	
	/**
	 *
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
				'postOnly + delete'); // we only allow deletion via POST request
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 *
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
				array(
						'allow', /* Acciones Permitidas */
									'actions' => array(
								'index',
								'view',
								'create',
								'update',
								'delete',
								'menu',
                                                                'exportexcel',
								'UpdateActive'),
						'users' => array(
								'*')),
				array(
						'deny',
						'users' => array(
								'*')));
	}
	
	public function __construct($id, $module = null)
	{
		parent::__construct($id, $module);
		
		Yii::app()->params['title'] = '';
	}

	public function actionExportexcel($id = null)
	{
		if (isset($_SESSION['promotion.excel']))
		{
			$data = $_SESSION['promotion.excel'];
			$hoy = date("Y-m-d H:i:s");     
			$this->toExcel($data, array('rol.descripcion','nombreusuario','email','nombre','apellido','razon_social','dni_numero','telf_local_numero'),$hoy);
		}
	}

	public function actionView($id)
	{
		if(Yii::app()->authRBAC->checkAccess($this->modulo . '_view'))
		{
			
			$model = $this->loadModel($id);
                        $model2 = new RBACUsuarios('tecnico');
			$model2->unsetAttributes();
                        if(isset($_GET['RBACUsuarios'])){
                            
                            $model2->attributes=$_GET['RBACUsuarios'];
                        }
			$this->render('view', array('model' => $model,'model2'=>$model2));
		}
		else
		{
			throw new CHttpException(403, Yii::app()->params['ErrorAccesoDenegado']);
		}
	}

	public function actionCreate()
	{
		if(Yii::app()->authRBAC->checkAccess($this->modulo . '_create') || isset($_POST['siteRegistro']))
		{
			$permitidos = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
			$asinc = false;
			$validPass = true;
			$fechaActual = date('d-m-Y h:m:s');
			$validateProgrammer = true;
			$estatus = 0;
			$model = new RBACUsuarios('create');
			$modelSO = new OperatingSystemsUser();
			$modelPL = new ProgrammingLanguagesUser();
			$modelPU = new ProductsUser();
			$modelRolesOp = new RBACRolesOpciones();
			// ///////////////////////////////////////////////////////////////////////////////////
			// BLOQUE PARA EL MANEJO DE REGISTRO DE USUARIOS PROVENIENTE DE LA VISTA DE LOGIN
			// SOLO SE REGISTRARAN USUARIOS DISTRIBUIDOR Y PROGRAMADOR
			if(isset($_POST['siteRegistro']))
			{
                           
				$asinc = true;
				$_POST['RBACUsuarios'] = json_decode($_POST['siteRegistro'], true);
				$estatus = 3;
				//$_POST['RBACUsuarios']['file'] = '';
				if($_POST['RBACUsuarios']['sistema_operativo'] != '' && $_POST['RBACUsuarios']['lenguaje_programacion'] != '' && $_POST['RBACUsuarios']['producto_integracion'] != '')
				{
					$modelSO->operatingsystem_id = $_POST['RBACUsuarios']['sistema_operativo'];
					$modelSO->created_at = $fechaActual;
					$modelSO->updated_at = $fechaActual;
					$modelPL->programming_languages_id = $_POST['RBACUsuarios']['lenguaje_programacion'];
					$modelPL->created_at = $fechaActual;
					$modelPL->updated_at = $fechaActual;
					$modelPU->product_id = $_POST['RBACUsuarios']['producto_integracion'];
					$modelPU->created_at = $fechaActual;
					$modelPU->updated_at = $fechaActual;
					$model->rol_id = 6;
				}
				else $validateProgrammer = false;
			}
			if(isset($_POST['RBACUsuarios']))
			{
                           // print_r($_POST); exit();
                                                      
                               	$model->estatus = $estatus;
				$model->attributes = $_POST['RBACUsuarios'];

				if(isset($_POST['RBACUsuarios']['address'])){
				$model->address = $_POST['RBACUsuarios']['address'];	
				}
				if(is_numeric($_POST['RBACUsuarios']['ruc_dv'])){
				$model->ruc_dv = $_POST['RBACUsuarios']['ruc_dv'];	
				} else {
					$model->ruc_dv = intval($_POST['RBACUsuarios']['ruc_dv']);	
				}
                                
                                if(isset($_POST['RBACUsuarios']['cod_saint'] )){
                                    $model->cod_saint=$_POST['RBACUsuarios']['cod_saint'];
                                }
				
				if(isset($_POST['RBACUsuarios']['softwarehouse']) && $_POST['RBACUsuarios']['softwarehouse'] != '')
				$model->$_POST['RBACUsuarios']['softwarehouse'];
				$model->registro_fecha = $this->getFecha();
				$model->registro_hora = $this->getHora();
				$model->registro_usuario_id = $asinc ? 4 : Yii::app()->user->id;
				$model->modificado_fecha = $this->getFecha();
				$model->modificado_hora = $this->getHora();
				$model->modificado_usuario_id = $asinc ? 4 : Yii::app()->user->id;
				$model->distribuidor_id = Yii::app()->user->getState('rol') == 3 ? Yii::app()->user->getState('id') : $_POST['RBACUsuarios']['distribuidor_id'];
				$erroUser = true;
				if($model->contrasena != '' && $model->contrasena != $_POST['RBACUsuarios']['confirmaPassword'])
				{
					$validPass = false;
				}
				$cadena = $model->nombreusuario;
				for ($i=0; $i<strlen($model->nombreusuario); $i++){
					if (strpos($permitidos, substr($cadena,$i,1))===false){
						$erroUser = false;
					}
				}
				if($model->rol_id != 3)
				{
					$model->razon_social = $model->nombre . ' ' . $model->apellido;
				}
                                //echo 'adsds'; exit();
				if($model->validate() && $validateProgrammer && $validPass && $erroUser)
				{
					$model->nombreusuario = strtolower($model->nombreusuario);
					//if(isset($_POST['RBACUsuarios']['file']) && $_POST['RBACUsuarios']['file'] != '')
                                        if(isset($_FILES['RBACUsuarios']) && $_FILES['RBACUsuarios']['name']['file'] != '')
					{
						$file = CUploadedFile::getInstance($model, "file");
                                                //$tmp = explode(".", $file->name);
                                                $tmp = explode(".", $_FILES['RBACUsuarios']['name']['file']);
						$extension = end($tmp);
						$name = $model->nombreusuario;
						$name = str_replace("_", " ", $name);
						$file->saveAs(Yii::getPathOfAlias("webroot") . "/img/profile/" . $name . "." . $extension);
						$model->file = $name . "." . $extension;
					}
					
					$pass = $model->contrasena;
					$model->contrasena = ValidateSafePassword::Hash($model->contrasena);
					if($model->save())
					{
						if(Yii::app()->user->getState('rol') == 3)
						{
							$model->distribuidor_id = Yii::app()->user->getState('id');
							$model->save();
						}
						elseif($model->rol_id != 8)
						{
							$model->distribuidor_id = $model->id;
							$model->save();
						}
						foreach ($modelRolesOp->findAll('rol_id = ' . $model->rol_id) as $value)
						{
							$modelRolesUser = new RBACRolesOpcionesUsuarios();
							$modelRolesUser->usuario_id = $model->id;
							$modelRolesUser->rol_opcion_id = $value['id'];
							$modelRolesUser->estatus = 1;
							$modelRolesUser->registro_fecha = date('Y-m-d');
							$modelRolesUser->registro_hora = date('H:m:s');
							$modelRolesUser->registro_usuario_id = (null !== Yii::app()->user->getState('id')) ? Yii::app()->user->getState('id') : 4;
							$modelRolesUser->modificado_fecha = date('Y-m-d');
							$modelRolesUser->modificado_hora = date('H:m:s');
							$modelRolesUser->modificado_usuario_id = (null !== Yii::app()->user->getState('id')) ? Yii::app()->user->getState('id') : 4;
							$modelRolesUser->secuencia = 1;
							$modelRolesUser->save();
						}
						//SE VALIDA LA DATA ASOCIADA A USUARIO PROGRAMADOR PROVENIENTE DE LA PANTALLA DE LOGIN.
						if($asinc)
						{
							$modelSO->user_id = $model->id;
							$modelPL->user_id = $model->id;
							$modelPU->user_id = $model->id;
							if(isset($_POST['siteRegistro']) && $modelSO->save() && $modelPL->save() && $modelPU->save())
							{
								//CORREOS INTERNOS QUE RECIBIRAN LA NOTIFICACION DE REGISTRO DE USUARIOS PROGRAMADORES
								$this->envioEmail(Yii::app()->params['correosInternos'], 'El usuario ' . Yii::app()->user->getState('nombreusuario') . 'registro a ' . $model->nombreusuario . ' con perfil ' . $model->rol->descripcion . ' para la extranet de Panama, y éste se encuentra a la espera de su activación.<br/>', 'The Factory Corp', 'Usuario Registrado');
								//CORREO DE CONFIRMACION DE REGISTRO ENVIADO AL USUARIO PROGRAMADOR REGISTRADO.
								$this->envioEmail($model->email, 'El registro para el usuario ' . $model->nombreusuario . ' fue exitosa. <br/>Su usuario es: ' . $model->nombreusuario . '<br/> Su contraseña : ' . $pass . '<br/>' . 'Espere a que el equipo de The Factory Corp verifique sus datos y proceda a su activación.<br/>', 'The Factory Corp', 'Usuario Registrado');
								echo CJSON::encode(array('message' => Yii::app()->params['msjsuccess'], 'success' => 'true'));
								return;
							}
							else
							{
								echo CJSON::encode(array('message' => Yii::app()->params['msjdanger'], 'success' => 'false'));
								return;
							}
						}
						else
						{
							//CORREOS INTERNOS QUE RECIBIRAN LA NOTIFICACION DE REGISTRO DE USUARIOS
							$correosInternos = Yii::app()->params['correosInternos'];

protected/modules/roles/views/perfil/_activos.php
<?php
Yii::app()->params['IDGridview'] = 'users-grid';
Yii::app()->params['rutaUrlGridviewBoxSwitch'] = Yii::app()->controller->createUrl('UpdateActive');
$active = array('0'=>'Inactivos','1'=>'Activos');

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#users-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
    $('.search-form').toggle();
    return false;
});
$('.search-form form').submit(function(){
    $('#users-grid').yiiGridView('update', {
        data: $(this).serialize()
    });
    return false;
});
");
?>
<input type="hidden" id="TOKEN" value="<?php echo Yii::app()->request->csrfToken ?>">
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading navbar-tool">

                <h3 class="panel-title"><?php echo Yii::app()->params['index-text']; ?> Usuarios</h3>

                <div class="menu-tool">

                    <div class="pagesize"> 
                        <?php $dataProvider = $this->PageSize(Yii::app()->params['IDGridview'], $model->search()); ?>
                    </div>                     

                    <div class="menu-items">
                        <?php  $this->widget('zii.widgets.CMenu', array('items' => $this->menu,'encodeLabel' => FALSE,'htmlOptions' => array('class' => 'cmenuhorizontal'),)); ?>
                    </div>
                </div>        
                <?php $this->ToolActionsRight(); ?>         

            </div>
            <div class="panel-body"> 
                <?php if (Yii::app()->authRBAC->checkAccess($this->modulo . '_create')) { ?>
                    <?php echo CHtml::link('Nuevo usuario', array('usuarios/create'), array('class' => 'btn btn-3d btn-primary')); ?>
                <?php } ?>
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id'=>Yii::app()->params['IDGridview'],       
                        'dataProvider' => $dataProvider,
                        'filter' => $model,
                        'columns' => array(                                                 
                            array('name' => 'rol_id', 'value' => '$data->rol->descripcion', 'type' => 'text', 'filter' => CHtml::listData(RBACRoles::model()->findAll('estatus = 1'), "id", "descripcion")),
                            array('name' => 'nombreusuario', 'value' => '$data->nombreusuario'),                          
                            array('name' => 'email', 'value' => '$data->email'),
                            array('name' => 'nombre', 'value' => '$data->nombre'),
                            array('name' => 'estatus','type' => 'raw','value' => 'Active::checkSwicth($data->estatus,$data->id)', 'filter' => Active::getListActive(),'htmlOptions' => array('class' => 'switchactive')
                            ),
                          
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['view-text'],
                                'label' => Yii::app()->params['view-icon'],
                                'linkHtmlOptions' => array('class' => 'view ' . Yii::app()->params['view-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("view",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_view')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['update-text'],
                                'label' => Yii::app()->params['update-icon'],
                                'linkHtmlOptions' => array('class' => 'edit ' . Yii::app()->params['update-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("update",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_update')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => 'Menu',
                                'label' => '<i class="fa fa-th"></i>',
                                'linkHtmlOptions' => array('class' => 'menu ' . Yii::app()->params['update-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("menu",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_update')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['delete-text'],
                                'label' => Yii::app()->params['delete-icon'],
                                'linkHtmlOptions' => array('class' => 'delete ' . Yii::app()->params['delete-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("delete",array("id"=>$data->id,"delete"=>$data->estatus))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_delete')
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
//if (Yii::app()->authRBAC->checkAccess($this->modulo . '_delete')) {
//
//    $this->ModalConfirmDelete(Yii::app()->params['IDGridview']);
//
//    $this->renderPartial('../../../../views/site/modal-delete', array());    
//}
?>

protected/modules/roles/views/perfil/_form.php
<?php
/* @var $this UsuariosController */
/* @var $model RBACUsuarios */
/* @var $form CActiveForm */
?>
<?php $form = $this->beginWidget('CActiveForm', array('id' => 'rbacusuarios-form', 'enableAjaxValidation' => false, 'htmlOptions' => array('enctype' => 'multipart/form-data', 'class' => 'form-horizontal', 'role' => 'form'),)); ?>


<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'rol_id'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->dropDownList($model, 'rol_id', CHtml::listData(RBACRoles::model()->findAll(), 'id', 'descripcion'), array((Yii::app()->user->getState('rol') == 2 || Yii::app()->controller->action->id == 'create') ? '' : "disabled"=>"disabled")); ?>
        <?php echo $form->error($model, 'rol_id'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'nombreusuario'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'nombreusuario', array('size' => 60, 'maxlength' => 100)); ?>

        <?php echo $form->error($model, 'nombreusuario'); ?>
    </div>

</div>

<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'contrasena'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->passwordField($model, 'contrasena', array('rows' => 60, 'cols' => 100)); ?>

        <?php echo $form->error($model, 'contrasena'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'email'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'email', array('size' => 60, 'maxlength' => 100)); ?>

        <?php echo $form->error($model, 'email'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'nombre'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'nombre', array('size' => 60, 'maxlength' => 100)); ?>

        <?php echo $form->error($model, 'nombre'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'apellido'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'apellido', array('size' => 60, 'maxlength' => 100)); ?>

        <?php echo $form->error($model, 'apellido'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'dni_numero'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'dni_numero', array('size' => 20, 'maxlength' => 20)); ?>

        <?php echo $form->error($model, 'dni_numero'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'telf_local_tipo'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'telf_local_tipo'); ?>

        <?php echo $form->error($model, 'telf_local_tipo'); ?>
    </div>

</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'telf_local_numero'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php echo $form->textField($model, 'telf_local_numero', array('size' => 7, 'maxlength' => 7)); ?>

        <?php echo $form->error($model, 'telf_local_numero'); ?>
    </div>


</div>
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'file'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <div class="col-xs-12 col-sm-9">
            <?php echo $form->FileField($model, 'file', array('size' => 7, 'maxlength' => 7)); ?>

            <?php echo $form->error($model, 'file'); ?>
        </div>
    </div>



</div>
<br />
<div class="form-group">
    <div class="col-xs-12 col-sm-3">
        <?php echo $form->labelEx($model, 'estatus'); ?>
    </div>

    <div class="col-xs-12 col-sm-9">
        <?php
        $this->widget('application.extensions.SwitchToggleJD.SwitchToggleJD', array(
            'id' => 'RBACUsuarios_estatus',
            'attribute' => 'RBACUsuarios[estatus]',
            'state' => $model->estatus,
            'type' => 'item',
            'coloron' => 'color1',
        ));
        ?>  

        <?php echo $form->error($model, 'estatus'); ?>
    </div>

</div>
<br />
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <p class="text-left">Campos con <span class="errorMessage">*</span> son requeridos.</p>
    </div>
    <div class="col-xs-12 col-sm-6">                
        <ul class="cmenuhorizontal" id="yw0">
            <li class="bottom"><?php echo CHtml::submitButton(Yii::app()->params['save-text'], array('class' => Yii::app()->params['save-btn'])); ?>
            </li>
            <li class="bottom"><?php echo CHtml::link(Yii::app()->params['cancel-text'], Yii::app()->controller->createUrl('index'), array('class' => Yii::app()->params['cancel-btn'])); ?>
            </li>
        </ul>
    </div>

</div>

<?php $this->endWidget(); ?>

protected/modules/roles/views/perfil/_pendiente.php
<?php
Yii::app()->params['IDGridview'] = 'users-pendiente-grid';
Yii::app()->params['rutaUrlGridviewBoxSwitch'] = Yii::app()->controller->createUrl('UpdateActive');
$active = array('0'=>'Inactivos','1'=>'Activos');

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#users-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
    $('.search-form').toggle();
    return false;
});
$('.search-form form').submit(function(){
    $('#users-grid').yiiGridView('update', {
        data: $(this).serialize()
    });
    return false;
});
");
?>
<input type="hidden" id="TOKEN" value="<?php echo Yii::app()->request->csrfToken ?>">
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading navbar-tool">

                <h3 class="panel-title"><?php echo Yii::app()->params['index-text']; ?> Usuarios</h3>

                <div class="menu-tool">

                    <div class="pagesize"> 
                        <?php $dataProvider = $this->PageSize(Yii::app()->params['IDGridview'], $model->pendiente()); ?>
                    </div>                     

                    <div class="menu-items">
                        <?php  $this->widget('zii.widgets.CMenu', array('items' => $this->menu,'encodeLabel' => FALSE,'htmlOptions' => array('class' => 'cmenuhorizontal'),)); ?>
                    </div>
                </div>        
                <?php $this->ToolActionsRight(); ?>         

            </div>
            <div class="panel-body"> 
                <?php if (Yii::app()->authRBAC->checkAccess($this->modulo . '_create')) { ?>
                    <?php echo CHtml::link('Nuevo usuario', array('usuarios/create'), array('class' => 'btn btn-3d btn-primary')); ?>
                <?php } ?>
                <div class="table-responsive">
                    <?php
                    $this->widget('zii.widgets.grid.CGridView', array(
                        'id'=>Yii::app()->params['IDGridview'],       
                        'dataProvider' => $dataProvider,
                        'filter' => $model,
                        'columns' => array(                                                 
                            array('name' => 'rol_id', 'value' => '$data->rol->descripcion', 'type' => 'text', 'filter' => CHtml::listData(RBACRoles::model()->findAll('estatus = 1'), "id", "descripcion")),
                            array('name' => 'nombreusuario', 'value' => '$data->nombreusuario'),                          
                            array('name' => 'email', 'value' => '$data->email'),
                            array('name' => 'nombre', 'value' => '$data->nombre'),
                            array('name' => 'estatus','type' => 'raw','value' => 'Active::checkSwicth($data->estatus,$data->id)', 'filter' => Active::getListActive(),'htmlOptions' => array('class' => 'switchactive')
                            ),
                          
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['view-text'],
                                'label' => Yii::app()->params['view-icon'],
                                'linkHtmlOptions' => array('class' => 'view ' . Yii::app()->params['view-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("view",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_view')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['update-text'],
                                'label' => Yii::app()->params['update-icon'],
                                'linkHtmlOptions' => array('class' => 'edit ' . Yii::app()->params['update-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("update",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_update')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => 'Menu',
                                'label' => '<i class="fa fa-th"></i>',
                                'linkHtmlOptions' => array('class' => 'menu ' . Yii::app()->params['update-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("menu",array("id"=>$data->id))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_update')
                            ),
                            array(
                                'class' => 'CLinkColumn',
                                'header' => Yii::app()->params['delete-text'],
                                'label' => Yii::app()->params['delete-icon'],
                                'linkHtmlOptions' => array('class' => 'delete ' . Yii::app()->params['delete-btn']),
                                'urlExpression' => 'Yii::app()->controller->createUrl("delete",array("id"=>$data->id,"delete"=>$data->estatus))',
                                'visible' => Yii::app()->authRBAC->checkAccess($this->modulo . '_delete')
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
//if (Yii::app()->authRBAC->checkAccess($this->modulo . '_delete')) {
//
//    $this->ModalConfirmDelete(Yii::app()->params['IDGridview']);
//
//    $this->renderPartial('../../../../views/site/modal-delete', array());    
//}
?>

protected/modules/roles/views/perfil/index.php
<?php
$this->widget('zii.widgets.jui.CJuiTabs',array(
    'tabs'=>array(      
        'Activos'=>array('id'=>'Activos','content'=>$this->renderPartial('_activos',array('model'=>$model),TRUE)),        
        'Pendiente por aprobar'=>array('id'=>'pendiente','content'=>$this->renderPartial('_pendiente',array('model'=>$model),TRUE)),                
    ),  
    'options'=>array('collapsible'=>true,),
    'id'=>'Usuarios',
));
?>